### ISSUE TITLE
possible regression in 0.30.x, produces http status code 500, "Server Error"

### ISSUE THREAD

**Issue by jasonjckn** [sunng87/ring-jetty9-adapter#113]
While attempting to move my codebase to 0.30.x, one of my unit tests started to fail. 

I narrowed this down as much as possible to a minimal example, 

Where the behaviour of rj9a 0.30.x and 0.22.x seem to diverge, is the point at which you send form params encoded as content-type JSON, then 0.30.x will give you http status code 500, and 0.22.1 will give you the correct output.

If you toggle between `:json` and `:edn`, you'll see what I mean. 
```
(POST! "/api" {:form-params      {:foobar 3}
                                                      :accept           :edn
                                                      :content-type     :json  ;; divergent behaviour between 0.22.x and 0.30.x
                                                      ;; :content-type     :edn ;; convergent behaviour between 0.22.x and 0.30.x
                                                      :throw-exceptions false
                                                      })
```  

[rj9a_bug.zip](https://github.com/sunng87/ring-jetty9-adapter/files/12556639/rj9a_bug.zip)

Run `$ ./reproduce.sh` 
to reproduce the bug, the way this script works is runs the program twice 

(1) with aliases `-M:dev:test:test-rj9a30`
(2) with aliases `-M:dev:test:test-rj9a22`

The script `./reproduce.sh`, expects (1) to fail and (2) to succeed,
IFF that happens you'll see the output "REPRODUCED BUG SUCCESSFULLY :)" 
Otherwise you haven't reproduced the divergent behaviour. 

It took me a while just to narrow this down to a reproducible example, i already spent a few hours on this, so going to go to sleep. I'll take another look tomorrow, to see if I can understand what's going on.

**Comment by sunng87** [comment]
if the issue might be related to middlewares, we can log request map to see if there is any difference between 0.30 and 0.22

**Comment by jasonjckn** [comment]
Thanks for the ideas, i'll try that tonight.

**Comment by jasonjckn** [comment]
This looks like a jetty 12.x issue as far as I can tell (?), and reproduces deterministically

<img width="967" alt="Screenshot 2023-09-08 at 10 05 06 PM" src="https://github.com/sunng87/ring-jetty9-adapter/assets/550839/f05d5a87-0695-4058-aa05-8eadce6f371e">

Here's where the stacktrace points to 
https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-io/src/main/java/org/eclipse/jetty/io/content/ContentSourceInputStream.java#L117

The most relevant part of rj9a code , would be 
https://github.com/sunng87/ring-jetty9-adapter/blob/master/src/ring/adapter/jetty9/common.clj#L88

But i don't see anything wrong. 
Here's the reproduction code, call $ ./reproduce.sh
[jetty12bug.zip](https://github.com/sunng87/ring-jetty9-adapter/files/12564714/jetty12bug.zip)

maybe @joakime or @lorban has insight here

**Comment by sunng87** [comment]
it seems `:character-encoding application/json` is wrong in 0.30. It is `UTF-8` in 0.22 and one of your middleware `muuntaja/format-negotiate-middleware` relies on this field.

**Comment by jasonjckn** [comment]
> it seems `:character-encoding application/json` is wrong in 0.30. It is `UTF-8` in 0.22 and one of your middleware `muuntaja/format-negotiate-middleware` relies on this field.

Yes here's the PR for that https://github.com/sunng87/ring-jetty9-adapter/pull/114
but this bug is different from that :)

**Comment by sunng87** [comment]
hmmm You are right. After fixing charset encoding field, we still have 500. And After printing exception in `SyncHandler`, I got exact stack trace:

``java.io.IOException: closed before EOF
	at org.eclipse.jetty.io.content.ContentSourceInputStream.close(ContentSourceInputStream.java:118)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:292)
	at com.fasterxml.jackson.core.base.ParserBase.close(ParserBase.java:392)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4833)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3809)
	at jsonista.core$eval6410$fn__6411.invoke(core.clj:207)
	at jsonista.core$eval6367$fn__6368$G__6358__6375.invoke(core.clj:177)
	at jsonista.core$read_value.invokeStatic(core.clj:243)
	at jsonista.core$read_value.invoke(core.clj:233)
	at muuntaja.format.json$decoder$reify__10564.decode(json.clj:36)
	at muuntaja.core$create_coder$decode__10965.invoke(core.clj:320)
	at muuntaja.core$create$_decode_request_body__11015.invoke(core.clj:422)
	at muuntaja.core$create$reify__11037.format_request(core.clj:476)`

```

**Comment by sunng87** [comment]
Http Request captured in Wireshark

```
E"}i@@¾jàb1Òæüáÿ
Ç!³Ç!±POST /api HTTP/1.1
Connection: close
content-type: application/json
accept: application/edn
accept-encoding: gzip, deflate
Content-Length: 12
Host: localhost:5600
User-Agent: Apache-HttpClient/4.5.13 (Java/17.0.8.1)

{"foobar":3}
```

Added some logging in `ContentSourceInputStream`, it shows the only chunk:

```
2023-09-09 16:02:25.214:INFO :oejic.ContentSourceInputStream:qtp238194056-30: reading chunk: WithRetainable@300dde8[l=false,b=DirectByteBufferR@28a480eb[p=226,l=238,c=8192,r=12]={POST /api....1)\r\n\r\n<<<{"foobar":3}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00}][Buffer@5defdb8f[rc=2,DirectByteBuffer@78d7c38d[p=238,l=238,c=8192,r=0]={POST /api...bar":3}<<<>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00}]]
```

`chunk.last()` returns `false` so calling `close` on `ContentSourceInputStream` raises error.

@lorban @sbordet you might want to check this bug

**Comment by sbordet** [comment]
@sunng87 reading that content directly through the `Request` should yield a last `Chunk`.
However, if you use `ContentSourceInputStream` you should read until you see `-1`.

I'm not sure what the problem is?
Do you see the `-1` while reading with `ContentSourceInputStream`?
If so, you should be good, and only after reading `-1` you can close the `ContentSourceInputStream`.

The other possibility is that we interpret `Connection: close` as a connection-delimited content even in presence of `Content-Length`, which would be wrong-ish although technically legal.

**Comment by jasonjckn** [comment]
@sbordet 

Is there any reason why a Request InputStream must be fully consumed before closing it? 

In a nutshell, the code seems to be calling `(org.eclipse.jetty.server.Request/asInputStream request)` then looking at the stack trace you see jackson readMapAndClose, 

I don't know for a fact this is the cause of the issue, but why can't jackson merely read 1 JSON map, and once it sees '}'... close the stream without producing an exception.

**Comment by sbordet** [comment]
> what's wrong with jackson-core merely read 1 JSON map, and once it sees }... close the stream without producing an exception "closed before EOF".

The lower layer that reads from the network has no idea of the format of the data it reads (whether it's JSON or some other format).
There are several cases I can think of right now, but there may be more:

* If `Transfer-Encoding: chunked`, the lower layer must read the terminal chunk `0\r\n\r\n` to know whether all content has been read.
* Connection-delimited content must read -1 at the TCP level to know whether all content has been read.
* When using HTTP/2 or HTTP/3 you may get all the JSON in one DATA frame with last=false, and few moments later an empty DATA frame with last=true.
* The lower layer may perform decoding (e.g. gzip) before presenting the data to the upper layer, and not reading up to -1 may leak resources.

So yes, read until you see -1 because that's the EOF definition. 
If you close the stream before, you have closed before EOF.

Having said that, it may be that we do not handle well in HTTP/1.1 the particular case of `Connection: close` together with `Content-Length` (we will check on that).

A good application should read until EOF so that it won't matter whether HTTP/1.1 is used, or HTTP/2, or HTTP/3 or `Transfer-Encoding: chunked`, etc. 
Reading until EOF will guarantee the same behavior across all the above cases.

See also https://github.com/FasterXML/jackson-jaxrs-providers/issues/108.

**Comment by jasonjckn** [comment]
Just wanted to double check a few assumptions, we're all on the mark here, as sbordet explained and shared https://github.com/FasterXML/jackson-jaxrs-providers/issues/108 

I'm able to reproduce/not reproduce the bug, based on disabling or enabling 
`(.enable com.fasterxml.jackson.databind.DeserializationFeature/FAIL_ON_TRAILING_TOKENS) ` 

[jetty12bug_b.zip](https://github.com/sunng87/ring-jetty9-adapter/files/12566886/jetty12bug_b.zip)

So the next question is where is the most appropriate place in the clojure stack we should address this at.

**Comment by jasonjckn** [comment]
@sbordet  @sunng87 

I encountered at least one scenario where FAIL_ON_TRAILING_TOKENS still won't consume the full request input stream, namely when the payload is invalid JSON. Also the thread you linked to https://github.com/FasterXML/jackson-jaxrs-providers/issues/108 can't verify this claim, but they stated " it will just either decode one token that follows, or throw exception encountering unexpected content.". 

How would you advise dealing with exceptional circumstances in general? e.g. the request stream would be consumed fully under normal circumstances, but there's any number of possible exceptions that can be thrown to prevent that (such as JSON parser error). So would you expect to see code like this (?) 

```
try { response = handler(req)  } 
catch (Throwable t) { while(req.body.read() != -1) {}; req.body.close(); } 
```

I've basically written exactly this... in clojure
A combination of _**disabling**_ stream close via Jackson  ObjectMapper 
``` 
(.disable (into-array com.fasterxml.jackson.core.JsonParser$Feature
                                       [com.fasterxml.jackson.core.JsonParser$Feature/AUTO_CLOSE_SOURCE]))
```
to prevent Jackson from closing the stream _**prematurely**_. 

Then in ring-jetty9-adapter 

<img width="524" alt="image" src="https://github.com/sunng87/ring-jetty9-adapter/assets/550839/07c30fdd-bf37-49dd-be4a-70776f6771ca">

Everythings working great now... honestly my intuition feels like this is badly designed code... but i don't do much low level HTTP code, so if you think this is good i'll send a PR for both ring-jetty9-adapter the `while true`, and metosin's muuntaja for AUTO_CLOSE_SOURCE

**Comment by sbordet** [comment]
Okay so there are few issues at play here, I'll try to address them.

About the first issue, the original report showed a stack trace with:

```
java.io.IOException: closed before EOF
        at org.eclipse.jetty.io.content.ContentSourceInputStream.close()
```

Jetty was a little too aggressive at reporting immediately a failure, so we made it a little friendlier in https://github.com/eclipse/jetty.project/issues/10513 (which is a issue with multiple sub-issues -- one of the sub-issue was discussing the behavior of `ContentSourceInputStream.close()`).

In Jetty 12.0.2 (soon to be released) in `ContentSourceInputStream.close()` Jetty tries one single read to try to read EOF, and if it succeeds it closes silently. 
This should take care of common cases (`Transfer-Encoding: chunked` and zipped streams, etc.), but only if the last "frame" is available to be read.
If `ContentSourceInputStream.close()` tries to read the EOF, but finds no data, it will still report a failure.

This first issue is related to a particular behavior of `ContentSourceInputStream.close()` used in the application (too aggressive), paired with the application not reading to EOF (so that `ContentSourceInputStream.close()` was happening before reading to EOF).

The second issue is that applications should still read until EOF.
Had you not used `ContentSourceInputStream`, the handling of the request would have returned into the Jetty implementation, where Jetty attempts to consume the request content until EOF, without blocking.
In most cases this would work, as the last "frame" would be there, and Jetty would read it non-blocking, discard it, and no error would be reported.
But it is always possible that the last "frame" is not there, and Jetty would report the error.
Note that this case differs from before because it happens in the Jetty implementation, not in the application.
Jetty tries its best effort to read until EOF, but the application has no control over this.

The last case is a JSON parsing error: what should applications do?
This is entirely in the hands of applications.
In case the application is using `ContentSourceInputStream`, upon its `close()` one more read will be attempted, probably finding more data but not EOF, and an error will be reported.
In case of not using `ContentSourceInputStream`, the application may let the JSON parsing exception unwind, which will be caught by the Jetty implementation that would try to consume the available request content without blocking, with a possibility of finding EOF (but also a possibility to not find it).

What should a client expect after sending broken JSON? 
Likely an error response, so probably applications on server-side should not try too hard to read EOF, as the JSON is bad and the client should be told about.

In summary:
* We improved `ContentSourceInputStream.close()` to be a bit friendlier in 12.0.2, probably covering 99.9% of cases, but it is still possible that an error is returned when the last "frame" is not there. For consistent behavior, applications should read until EOF before closing `ContentSourceInputStream`.
* When not using `ContentSourceInputStream`, Jetty will try to read the request content until EOF, but there is no guarantee it will reach EOF. For consistent behavior, applications should read until EOF.
* In case of JSON parsing errors, the application must decide. It may:
A) try to read and discard the remaining request content until EOF.
B) give up reading and let the failure flow out, so that Jetty will try to read until EOF and return an error response.
C) give up reading, explicitly send an error response, return from handling, where Jetty will try to read until EOF.

Personally, putting on the application writer hat, in case of JSON parsing errors I would not bother trying to read until EOF.

But with the Jetty library writer hat, we try our best effort to read until EOF non-blocking, but sometimes we just cannot and a failure will surface.

**Comment by sbordet** [comment]
FTR, also look at this test case, which I found having completely unexpected behavior:
https://github.com/eclipse/jetty.project/blob/jetty-12.0.x/jetty-core/jetty-tests/jetty-test-client-transports/src/test/java/org/eclipse/jetty/test/client/transport/ZippedRequestContentTest.java

Reading from `ZipInputStream` until `getNextEntry()` returns `null` is not enough to consume the zip stream, because there is the zip trailer that needs to be read.

Unfortunately, `ZipInputStream` does not give developers zip specific APIs to read the zip trailer, nor it does it in its `close()` method, so to be consistent the application must read the non-zipped `InputStream` until the end.

Note that Jetty does not know that the non-zipped `InputStream` is `zip` encoded, it just sees that there are more bytes to read (the zip trailer bytes) but the application did not read them.

I would have expected `ZipInputStream.getNextEntry()` to return `null` when the stream was at EOF, but it is not the case.

**Comment by sunng87** [comment]
@jasonjckn In #118 I have upgraded jetty to 12.0.2, maybe you can test if the improvement in `ContentSourceInputStream.close()` fixes the issue

**Comment by jasonjckn** [comment]
This issue no longer reproduces [feature/jetty-12-0-2-update](https://github.com/sunng87/ring-jetty9-adapter/tree/feature/jetty-12-0-2-update) 

I did 3 tests, 

(1) info.sunng/ring-jetty9-adapter {:mvn/version "0.30.0"}

Issue reproduces

(2) vanilla feature/jetty-12-0-2-update

issue does not reproduce 

(3) feature/jetty-12-0-2-update without buffered output stream 
<img width="517" alt="image" src="https://github.com/sunng87/ring-jetty9-adapter/assets/550839/fe60794e-8e7b-4620-a272-8158b5225a43">

issue does not reproduce 


I guess the resolution was somewhere in what @sbordet wrote, "We improved ContentSourceInputStream.close() to be a bit friendlier in 12.0.2, " so thank you for that! 

This won't require any muuntaja changes, everything just works as far as I can tell.
